"""make tables dynamically with sqlalchemy from base models

Revision ID: 7f9a1e2be03c
Revises: f8ff0045d4dc
Create Date: 2024-05-17 14:22:26.589337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9a1e2be03c'
down_revision: Union[str, None] = 'f8ff0045d4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
